import { Inter } from 'next/font/google'
import './globals.css'
import Navbar_1 from './Components/Navbar_1'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Sarthak Store',
  description: 'Generated by create next app',
}

 export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <meta name="viewport" content="width=device-width, initial-scale=1.0"/>

      <body className='bg-gray-100'>
      
        {children}</body>
    </html>
  )
}
